version: "3.2"
services:
  rabbitmq:
    image: rabbitmq
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
    networks:
        - internal_network
  app_server:
    ports:
      - 3000:3000
    networks:
      - internal_network
    container_name: 'app_server'
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - internal_network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    networks:
      - internal_network
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/var/lib/grafana/dashboards


networks:
  internal_network:
    external: true
  
volumes:
  grafana_data: