version: "3.2"
services:
  rabbitmq:
    image: rabbitmq
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
    networks:
        - internal_network
  app_server:
    ports:
      - 3000:3000
    networks:
      - internal_network
    container_name: 'app_server'
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    restart: always


networks:
  internal_network:
    external: true