global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'app_server'
    static_configs:
      - targets: ['app_server:3000']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
